# Generated by Django 3.2.6 on 2021-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210804_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
