# Generated by Django 3.2.6 on 2021-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210804_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='barcode',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
